### ISSUE TITLE
Nested query not working

### ISSUE THREAD

**Issue by sanginovs** [blb-ventures/strawberry-django-plus#117] opened 2022-09-13 02:41 UTC
Hi @bellini666 
I can't seem to get this nested queries to work. Can you take a look at what's wrong with this?

```

vehicle(vin: "xyz") {
        year
        photoUrls {
             url
        }
  }

```

Keep getting this error: **Vehicle' object has no attribute 'photoUrls'**

<img width="374" alt="Screen Shot 2022-09-12 at 7 40 42 PM" src="https://user-images.githubusercontent.com/16856287/189795586-6796568d-a7d6-4ae1-a5f2-824fde626f2e.png">

**Here's my code:**

```
**models.py**

class Vehicle(models.Model):
     year = models.IntegerField(blank=False)
     
     
class PhotoUrls(models.Model):
    url = models.CharField(max_length=2048, blank=True)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    
    
 **types.py**
 
@gql.django.type(models.Vehicle)
class VehicleType:
     year: gql.auto
     photoUrls: List["PhotoUrlsType"]
 

@gql.django.type(models.PhotoUrls)
class PhotoUrlsType:
    url: gql.auto
    vehicle: VehicleType
    
    
 **schema.py**
  
 @gql.type
class Query:
      
    @gql.django.field
    def photoUrls(self, info, vin: str) -> List[PhotoUrlsType]:
        vehicle = Vehicle.objects.filter(vin=vin).first()
        urls = PhotoUrls.objects.filter(vehicle=vehicle)
        return [url for url in urls]

     @gql.django.field
    def vehicle(self, info, vin: str) -> Optional[VehicleType]:
           user = info.context.request.user
           if not user.is_authenticated:
               return None
           vehicle = Vehicle.objects.filter(vin=vin).first()
           return vehicle
```

**Comment by bellini666** [comment] 2022-09-15 15:16
@sanginovs the issue is that you declared the attributes with camelCase. You should use snake_case in python so that it matches the attribute in the django model (i.e. `photo_urls` instead of `photoUrls`. strawberry will automatically convert to camelCase when exposing the schema

Try that and let me know if it works

**Comment by sanginovs** [comment] 2022-09-18 19:22
@bellini666 Tried this but keep getting the same error. I changed to snake_case like this:


``` 
 **types.py**
 
@gql.django.type(models.Vehicle)
class VehicleType:
     year: gql.auto
     photo_urls: List["PhotoUrlsType"]
 ...

 **schema.py**
  
 @gql.type
class Query:
      
    @gql.django.field
    def photo_urls(self, info, vin: str) -> List[PhotoUrlsType]:
        vehicle = Vehicle.objects.filter(vin=vin).first()
        urls = PhotoUrls.objects.filter(vehicle=vehicle)
        return [url for url in urls]
   ...

```

**Comment by sanginovs** [comment] 2022-09-18 19:57
Update:

I was able to make this work by explicitly specifying photo_url resolver in Vehicle's photo_urls property. 
I removed a field resolver for photoUrls. Instead i just created a local resolver function for photoUrls and referenced it in VehicleType's photo_urls property. 

```
**types.py**

def photo_urls_resolver(self, info, vin: str) -> List["PhotoUrlsType"]:
    vehicle = Vehicle.objects.filter(vin=vin).first()
    urls = PhotoUrls.objects.filter(vehicle=vehicle)
    return [url for url in urls]

@gql.django.type(models.Vehicle)
class VehicleType:
    year: gql.auto
    photo_urls: List["PhotoUrlsType"] = gql.django.field(resolver=photo_urls_resolver)

@gql.django.type(models.PhotoUrls)
class PhotoUrlsType:
    url: gql.auto
    vehicle: VehicleType

```


and ran this query and it works:

```

query {
  vehicle(vin: "xyz") {
    vin 
    photoUrls(vin: "xyz") {
      url
    }
  }
}

 ```

**Comment by bellini666** [comment] 2022-09-20 19:20
The decorated function does the same as the resolver argument, but glad it worked for you! :)

I'm closing the issue now. Feel free to open more if you find any other issues

**Closed by bellini666** 2022-09-20 19:20 UTC
Labels: question
