### ISSUE TITLE
NodeExtension broken with Strawberry

### ISSUE THREAD

**Issue by djstein** [blb-ventures/strawberry-django-plus#246] opened 2023-06-17 21:25 UTC
when making single item Relay based Node calls that use of `gql.django.node` in queries such as:

```python
@strawberry.type
class Query:
    item: Item = gql.django.node()
```

The use of the NodeExtension at https://github.com/blb-ventures/strawberry-django-plus/blob/main/strawberry_django_plus/field.py#L637 results in the following related error https://github.com/strawberry-graphql/strawberry/issues/2862

**Comment by bellini666** [comment] 2023-06-18 16:27
Hey @djstein ,

Thanks for pointing it out!

[This PR](https://github.com/strawberry-graphql/strawberry/pull/2863) should fix the issue for both strawberry and for this lib as well. Since the issue is already opened there, and the fix is on strawberry's side, I'll close this. But feel free to reopen it if required :)

**Closed by bellini666** 2023-06-18 16:27 UTC
